/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Knapsack;

/**
 *
 * @author benfredette
 */
public class KnapSackNR {
    private int[] v; //value of items
    private int[] w; // Weight of items
    private int W, n; //Weight of the knapsack
    private int[][] soln;
    public KnapSackNR(int[] v, int[] w, int W){
        this.v = v;
        this.w = w;
        this.W = W;
        this.n = v.length;
        this.soln = new int[v.length + 1][W + 1]; //Solution matrix generated by dynamic programming
    }
    
    public int SolveKS(){
        //Initialize first row of solution to 0
        for(int i = 0; i <= this.W; i++){
            this.soln[0][i] = 0;
        }
        
        //Loop through all weights (1 to W) for each item i in the range 1 to n
        for(int i = 1; i <= n; i++){
            for(int j = 1; j <= this.W; j++){
                //Do not include ith item by default
                soln[i][j] = soln[i - 1][j];
                //If weight of item i is <= current weight j, two options: 
                if(this.w[i-1] <= j){ //If ith item can fit in knapsack
                    //Include the item or dont include depending on which one gives max
                    this.soln[i][j] = Math.max(v[i-1]+ soln[i-1][j - this.w[i-1]], soln[i][j]);
                }
            }
        }
        return this.soln[n][W];
    }
    
    
}
